version: '3'

vars:
  CLI_NAME: acton
  CLI_PATH: acton-cli
  SERVICE_PATH: acton-service
  INSTALL_DIR: '{{.HOME}}/.local/bin'
  TARGET_DIR: target/release

tasks:
  build:
    desc: Build the CLI in release mode
    cmds:
      - cargo build --manifest-path {{.CLI_PATH}}/Cargo.toml --release
    sources:
      - '{{.CLI_PATH}}/src/**/*.rs'
      - '{{.CLI_PATH}}/Cargo.toml'
    generates:
      - '{{.TARGET_DIR}}/{{.CLI_NAME}}'

  install:
    desc: Install the CLI to ~/.local/bin
    deps:
      - build
    cmds:
      - mkdir -p {{.INSTALL_DIR}}
      - cp {{.TARGET_DIR}}/{{.CLI_NAME}} {{.INSTALL_DIR}}/{{.CLI_NAME}}
      - chmod +x {{.INSTALL_DIR}}/{{.CLI_NAME}}
    status:
      - test -f {{.INSTALL_DIR}}/{{.CLI_NAME}} && test {{.TARGET_DIR}}/{{.CLI_NAME}} -ot {{.INSTALL_DIR}}/{{.CLI_NAME}}

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean --manifest-path {{.CLI_PATH}}/Cargo.toml

  uninstall:
    desc: Remove the CLI from ~/.local/bin
    cmds:
      - rm -f {{.INSTALL_DIR}}/{{.CLI_NAME}}

  changelog:
    desc: Generate CHANGELOG.md from git history
    summary: |
      Generate or update the CHANGELOG.md file using git-cliff.

      Usage:
        task changelog              # Generate full changelog
        task changelog -- --unreleased  # Show only unreleased changes

      Requires:
      - git-cliff installed (cargo install git-cliff)
    cmds:
      - git-cliff -o CHANGELOG.md {{.CLI_ARGS}}

  changelog-preview:
    desc: Preview changelog without writing to file
    summary: |
      Preview what the changelog would look like without modifying CHANGELOG.md.

      Usage:
        task changelog-preview              # Preview full changelog
        task changelog-preview -- --unreleased  # Preview unreleased changes only
    cmds:
      - git-cliff {{.CLI_ARGS}}

  changelog-unreleased:
    desc: Show unreleased changes since last tag
    cmds:
      - git-cliff --unreleased

  audit:
    desc: Run cargo-audit to check for known vulnerabilities
    cmds:
      - cargo audit

  deny:
    desc: Run cargo-deny checks (advisories, licenses, bans, sources)
    summary: |
      Run cargo-deny to check dependency policies.

      Usage:
        task deny                          # Run all checks
        task deny -- check advisories      # Run specific check

      Requires:
      - cargo-deny installed (cargo install cargo-deny)
    cmds:
      - cargo deny check {{.CLI_ARGS | default "all"}}

  sbom:
    desc: Generate CycloneDX SBOM in JSON format
    cmds:
      - cargo cyclonedx --manifest-path Cargo.toml --format json --all

  security:
    desc: Run all security checks (audit, deny, sbom)
    cmds:
      - task: audit
      - task: deny
      - task: sbom

  release-cli:
    desc: Bump CLI version, update changelog, sign, and push to remote (no publish)
    summary: |
      Release a new version of the CLI using cargo-release.

      Usage:
        task release-cli -- patch   # Bump patch version (0.2.1 -> 0.2.2)
        task release-cli -- minor   # Bump minor version (0.2.1 -> 0.3.0)
        task release-cli -- major   # Bump major version (0.2.1 -> 1.0.0)

      This will:
      - Bump the version in Cargo.toml
      - Update CHANGELOG.md with git-cliff
      - Create a signed git commit
      - Create a signed git tag
      - Push changes and tags to remote
      - NOT publish to crates.io (--no-publish)

      Requires:
      - cargo-release installed (cargo install cargo-release)
      - git-cliff installed (cargo install git-cliff)
      - GPG signing configured
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Error: Version level required (patch, minor, or major)"
          echo "Usage: task release-cli -- patch"
          exit 1
        fi
      - git-cliff -o CHANGELOG.md
      - git add CHANGELOG.md
      - cargo release --manifest-path {{.CLI_PATH}}/Cargo.toml --sign --no-publish -x {{.CLI_ARGS}}

  release-service:
    desc: Bump acton-service version, update changelog, sign, publish, and push
    summary: |
      Release a new version of the acton-service crate using cargo-release.

      Usage:
        task release-service -- patch   # Bump patch version (0.2.1 -> 0.2.2)
        task release-service -- minor   # Bump minor version (0.2.1 -> 0.3.0)
        task release-service -- major   # Bump major version (0.2.1 -> 1.0.0)

      This will:
      - Bump the version in Cargo.toml
      - Update CHANGELOG.md with git-cliff
      - Create a signed git commit
      - Create a signed git tag
      - Publish to crates.io
      - Push changes and tags to remote

      Requires:
      - cargo-release installed (cargo install cargo-release)
      - git-cliff installed (cargo install git-cliff)
      - GPG signing configured
      - crates.io authentication (cargo login)
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Error: Version level required (patch, minor, or major)"
          echo "Usage: task release-service -- patch"
          exit 1
        fi
      - git-cliff -o CHANGELOG.md
      - git add CHANGELOG.md
      - cargo release --manifest-path {{.SERVICE_PATH}}/Cargo.toml --sign -x {{.CLI_ARGS}}

  default:
    desc: Build and install the CLI
    cmds:
      - task: install
