version: '3'

vars:
  CLI_NAME: acton
  CLI_PATH: acton-cli
  INSTALL_DIR: '{{.HOME}}/.local/bin'
  TARGET_DIR: target/release

tasks:
  build:
    desc: Build the CLI in release mode
    cmds:
      - cargo build --manifest-path {{.CLI_PATH}}/Cargo.toml --release
    sources:
      - '{{.CLI_PATH}}/src/**/*.rs'
      - '{{.CLI_PATH}}/Cargo.toml'
    generates:
      - '{{.TARGET_DIR}}/{{.CLI_NAME}}'

  install:
    desc: Install the CLI to ~/.local/bin
    deps:
      - build
    cmds:
      - mkdir -p {{.INSTALL_DIR}}
      - cp {{.TARGET_DIR}}/{{.CLI_NAME}} {{.INSTALL_DIR}}/{{.CLI_NAME}}
      - chmod +x {{.INSTALL_DIR}}/{{.CLI_NAME}}
    status:
      - test -f {{.INSTALL_DIR}}/{{.CLI_NAME}} && test {{.TARGET_DIR}}/{{.CLI_NAME}} -ot {{.INSTALL_DIR}}/{{.CLI_NAME}}

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean --manifest-path {{.CLI_PATH}}/Cargo.toml

  uninstall:
    desc: Remove the CLI from ~/.local/bin
    cmds:
      - rm -f {{.INSTALL_DIR}}/{{.CLI_NAME}}

  release:
    desc: Bump CLI version, sign, and push to remote (no publish)
    summary: |
      Release a new version of the CLI using cargo-release.

      Usage:
        task release -- patch   # Bump patch version (0.2.1 -> 0.2.2)
        task release -- minor   # Bump minor version (0.2.1 -> 0.3.0)
        task release -- major   # Bump major version (0.2.1 -> 1.0.0)

      This will:
      - Bump the version in Cargo.toml
      - Create a signed git commit
      - Create a signed git tag
      - Push changes and tags to remote
      - NOT publish to crates.io (--no-publish)

      Requires:
      - cargo-release installed (cargo install cargo-release)
      - GPG signing configured
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Error: Version level required (patch, minor, or major)"
          echo "Usage: task release -- patch"
          exit 1
        fi
      - cargo release --manifest-path {{.CLI_PATH}}/Cargo.toml --sign --no-publish -x {{.CLI_ARGS}}

  default:
    desc: Build and install the CLI
    cmds:
      - task: install
